declare class modal extends DsynrUIIElement {
    parent: HTMLElement;
    content: HTMLElement;
    root: HTMLElement;
    namePrefix: string;
    nameSuffix: string;
    show(): void;
    hide(): void;
    destroy(): void;
    defaults(): void;
    updatePref(preferences: object): void;
    setup(): void;
    setActive(): void;
    private context;
    private theModal;
    private underlay;
    private rootClasses;
    private modalClasses;
    private underlayClasses;
    private overlayClasses;
    private animationClasses;
    private prefix;
    private suffix;
    private disableUnderlay;
    private useOverlay;
    private isOverlayOn;
    private animate;
    constructor(modalContent: HTMLElement, preferences?: object);
    private stringup;
    showBlanket(): void;
    hideBlanket(): void;
    blanketHidden(event: any): void;
    closeCurModal(): void;
    align(): void;
    modalHidden(event: any): void;
}
declare function autoModalize(modalClass?: string): void;
declare let activeModal: HTMLElement, totModals: number, modals: Array<modal>;
