declare class Modal extends DsynrUIIElement {
    parent: HTMLElement;
    itself: HTMLElement;
    content: HTMLElement;
    root: HTMLElement;
    namePrefix: string;
    nameSuffix: string;
    protected underlay: HTMLElement;
    protected rootClasses: string;
    protected modalClasses: string;
    protected underlayClasses: string;
    protected overlayClasses: string;
    protected animationClasses: string;
    protected disableUnderlay: boolean;
    protected useOverlay: boolean;
    protected isOverlayOn: boolean;
    protected animate: boolean;
    constructor(modalContent: HTMLElement, preferences?: object);
    show(): void;
    hide(): void;
    destroy(): void;
    protected defaults(): void;
    updatePref(preferences: object): void;
    protected setup(): void;
    protected setActive(): void;
    protected stringup(strings: Array<any>, seperator?: string): string;
    showBlanket(): void;
    hideBlanket(): void;
    blanketHidden(event: any): void;
    align(): void;
    protected modalHidden(event: any): void;
}
declare function autoModalize(modalClass?: string): void;
declare let modals: Array<Modal>;
